INSERT INTO Violazioni (Descizione)
VALUES 
('Il soggetto era ubriaco marcio e urlava tantissimo'),
('Guida in stato di ebbrezza'),
('Eccesso di velocità'),
('Mancato rispetto del semaforo rosso'),
('Guida senza cintura di sicurezza'),
('Utilizzo del cellulare mentre si guida'),
('Guida contromano'),
('Fuga dopo incidente'),
('Guida senza patente'),
('Guida senza assicurazione'),
('Veicolo non conforme alle normative di sicurezza'),
('Sosta in divieto di fermata'),
('Occupazione abusiva del suolo pubblico'),
('Conducente senza casco'),
('Conducente non in possesso della revisione obbligatoria'),
('Conducente senza documenti di identità'),
('Trasporto di merci pericolose senza autorizzazione'),
('Veicolo rubato'),
('Trasporto di animali senza autorizzazione'),
('Guida senza occhiali correttivi'),
('Veicolo senza assicurazione'),
('Sosta in zona vietata'),
('Guida in stato di alterazione psicofisica'),
('Veicolo senza revisione tecnica'),
('Trasporto di rifiuti non autorizzato'),
('Guida senza rispettare le distanze di sicurezza'),
('Eccesso di rumore del veicolo'),
('Trasporto di persone in modo pericoloso'),
('Manomissione del tachigrafo'),
('Guida senza illuminazione adeguata'),
('Guida senza rispettare le precedenze'),
('Trasporto di sostanze stupefacenti'),
('Veicolo senza assicurazione RCA'),
('Guida senza la prescritta preparazione professionale'),
('Conducente senza autorizzazione al trasporto pubblico'),
('Guida senza revisione medica'),
('Veicolo senza contrassegno di circolazione'),
('Guida senza rispettare i limiti di velocità'),
('Guida con targa contraffatta'),
('Trasporto di merci in sovraccarico');
